language: c

before_install:
  - sudo apt-get install -qq mono-devel mono-gmcs nunit-console

script:
  - xbuild src/Frankie.sln /verbosity:minimal /t:Clean /t:Build /p:Configuration=Release
  - nunit-console src/Tests/bin/Release/RDumont.Frankie.Tests.dll -xml=UnitTestsResult.xml -exclude:windows_only
  - nunit-console src/Specs/bin/Release/RDumont.Frankie.Specs.dll -xml=SpecFlowTestsResult.xml -exclude:windows_only